name: CI/CD - Deploy on main

on:
  push:
    branches:
      - main  # Déclenchement à chaque push sur main
  workflow_dispatch: # Permet aussi de le lancer manuellement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build step (simulé ici)
        run: |
          echo "Build du projet..."
          mkdir -p build
          cp index.html build/

      - name: Deploy step (simulé ici)
        run: |
          echo "Déploiement en cours..."
          ls -la build

